# Two stages. The first compiles NBIS and is thrown away; the second is the
# image a run uses. Only one file crosses the boundary.
#
# Both stages start from the same pinned base. The binary built in the first is
# copied into the second, so it must not need a newer glibc than the second
# has; sharing one base makes that impossible to get wrong, and there is one
# digest to keep current instead of two. The base is Debian bookworm, which is
# what python:3.12-slim-bookworm is built on.

# The base is pinned by digest, not by tag. A tag moves: python:3.12-slim-bookworm
# points at a different image every time the upstream is rebuilt, and a run
# recorded against a tag cannot be reproduced. The digest is resolved with
# "docker buildx imagetools inspect"; the command and its output are recorded in
# docs/container.md.
FROM python:3.12-slim-bookworm@sha256:782412e85d0f0984994c290652577d4018aff08145c85b262bb63dc0c7522254 AS nbis-builder

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

# A third-party mirror, not a NIST release: NIST distributes NBIS behind a
# request form that a build cannot fetch. The commit is pinned; a branch would
# make the image depend on whatever the mirror holds on the day it is built.
# What this costs, and why it is accepted, is in quality/REF-005.
ARG NBIS_REPO=https://github.com/lessandro/nbis
ARG NBIS_COMMIT=3d3b05f0144b706bed56407957bc00779baf2fa5
RUN git clone "${NBIS_REPO}" . \
    && git checkout --quiet "${NBIS_COMMIT}" \
    && test "$(git rev-parse HEAD)" = "${NBIS_COMMIT}"

# setup.sh refuses an install directory that does not exist, so it is created
# first. Nothing is installed there that leaves this stage; the runtime image
# takes one binary out of the build tree.
RUN mkdir -p /usr/local/nbis \
    && ./setup.sh /usr/local/nbis --without-X11 --64

# GCC 10 changed the default from -fcommon to -fno-common, so tentative
# definitions the linker used to merge now collide, and the build dies in
# an2k/histogen with "multiple definition of 'histo_head'" — a component this
# project never uses. rules.mak is generated by setup.sh, so the flag is added
# afterwards, and the patch is asserted rather than assumed: if line 142 ever
# moves, the build stops here instead of failing later for a reason that reads
# as unrelated.
RUN sed -i '142s/-O2 -w -ansi/-O2 -w -ansi -fcommon/' rules.mak \
    && sed -n '142p' rules.mak \
    && sed -n '142p' rules.mak | grep -q -- '-fcommon'

# The whole tree, not one package: the packages share libraries, and pruning
# the build introduces failures of its own. Building everything and copying one
# binary out is the cheaper shape.
RUN make config && make it


FROM python:3.12-slim-bookworm@sha256:782412e85d0f0984994c290652577d4018aff08145c85b262bb63dc0c7522254

# Exact versions, and only these. Every package in the image is a field of the
# environment a run record has to name, so the set is kept small and fixed
# rather than resolved at build time. Pillow is here because mindtct reads PNG
# and the datasets ship TIFF.
RUN pip install --no-cache-dir \
        numpy==2.5.2 \
        pytest==9.1.1 \
        pillow==12.3.0

# One file crosses the stage boundary. No compiler, no source tree, no other
# NBIS tool. mindtct links only libm and libc — libpng and zlib are static
# inside it — so the runtime needs no extra packages; scripts/check_tools.sh
# checks that with ldd rather than trusting the claim.
COPY --from=nbis-builder /src/mindtct/bin/mindtct /usr/local/bin/mindtct

WORKDIR /work

# /work is a bind mount, not a copy. The image pins the environment, git pins
# the code, and a run record names both; copying the repository in would merge
# the two and make an edit require a rebuild.
ENV PYTHONPATH=/work

# No .pyc files: they would be written into the bind mount, which is the
# author's working tree.
ENV PYTHONDONTWRITEBYTECODE=1
