# Two stages. The first compiles NBIS and is thrown away; the second is the
# image a run uses. Only one file crosses the boundary.
#
# Both stages start from the same pinned base. The binary built in the first is
# copied into the second, so it must not need a newer glibc than the second
# has; sharing one base makes that impossible to get wrong, and there is one
# digest to keep current instead of two. The base is Debian bookworm, which is
# what python:3.12-slim-bookworm is built on.

# The base is pinned by digest, not by tag. A tag moves: python:3.12-slim-bookworm
# points at a different image every time the upstream is rebuilt, and a run
# recorded against a tag cannot be reproduced. The digest is resolved with
# "docker buildx imagetools inspect"; the command and its output are recorded in
# docs/container.md.
FROM python:3.12-slim-bookworm@sha256:782412e85d0f0984994c290652577d4018aff08145c85b262bb63dc0c7522254 AS nbis-builder

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

# The publisher's own archive, pinned by checksum. NIST serves it over plain
# HTTPS with no registration, so nothing stands between the build and the
# release. The checksum is verified before a single file is unpacked, and
# sha256sum -c exits non-zero on a mismatch, which stops the build instead of
# warning. quality/REF-005 records why the source of record is the publisher's
# archive rather than the mirror this recipe was first worked out against.
#
# The archive unpacks into a top-level Rel_5.0.0 directory; its contents are
# moved into /src so that the build tree sits where the rest of this file
# expects it.
ARG NBIS_URL=https://nigos.nist.gov/nist/nbis/nbis_v5_0_0.zip
ARG NBIS_SHA256=0adf8ab0f6b0e4208de50ca00ba21d3d77112ecd66288757ddfed21f6bee92c3
RUN curl -fsSL --retry 3 -o /tmp/nbis.zip "${NBIS_URL}" \
    && echo "${NBIS_SHA256}  /tmp/nbis.zip" | sha256sum -c - \
    && unzip -q /tmp/nbis.zip -d /tmp/nbis \
    && mv /tmp/nbis/Rel_5.0.0/* /src/ \
    && rm -rf /tmp/nbis.zip /tmp/nbis

# setup.sh refuses an install directory that does not exist, so it is created
# first. Nothing is installed there that leaves this stage; the runtime image
# takes one binary out of the build tree.
RUN mkdir -p /usr/local/nbis \
    && ./setup.sh /usr/local/nbis --without-X11 --64

# GCC 10 changed the default from -fcommon to -fno-common, so tentative
# definitions the linker used to merge now collide, and the build dies in
# an2k/histogen with "multiple definition of 'histo_head'" — a component this
# project never uses. rules.mak is generated by setup.sh, so the flag is added
# afterwards, and the patch is asserted rather than assumed: if line 142 ever
# moves, the build stops here instead of failing later for a reason that reads
# as unrelated.
RUN sed -i '142s/-O2 -w -ansi/-O2 -w -ansi -fcommon/' rules.mak \
    && sed -n '142p' rules.mak \
    && sed -n '142p' rules.mak | grep -q -- '-fcommon'

# The whole tree, not one package: the packages share libraries, and pruning
# the build introduces failures of its own. Building everything and copying one
# binary out is the cheaper shape.
RUN make config && make it


FROM python:3.12-slim-bookworm@sha256:782412e85d0f0984994c290652577d4018aff08145c85b262bb63dc0c7522254

# Exact versions, and only these. Every package in the image is a field of the
# environment a run record has to name, so the set is kept small and fixed
# rather than resolved at build time. Pillow is here because mindtct reads PNG
# and the datasets ship TIFF.
RUN pip install --no-cache-dir \
        numpy==2.5.2 \
        pytest==9.1.1 \
        pillow==12.3.0

# One file crosses the stage boundary. No compiler, no source tree, no other
# NBIS tool. mindtct links only libm and libc — libpng and zlib are static
# inside it — so the runtime needs no extra packages; scripts/check_tools.sh
# checks that with ldd rather than trusting the claim.
COPY --from=nbis-builder /src/mindtct/bin/mindtct /usr/local/bin/mindtct

WORKDIR /work

# /work is a bind mount, not a copy. The image pins the environment, git pins
# the code, and a run record names both; copying the repository in would merge
# the two and make an edit require a rebuild.
ENV PYTHONPATH=/work

# No .pyc files: they would be written into the bind mount, which is the
# author's working tree.
ENV PYTHONDONTWRITEBYTECODE=1
